<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" class="form-control" placeholder="Nome" name="nome">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email'] ?>" class="form-control" placeholder="E-mail" name="email">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha'] ?>" class="form-control" placeholder="Senha" name="senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

              <?php if($this->view->erroCadastro == 'email'){ ?>
                <h6 class='form-text text-danger text-center'>
                  *Este email já está em uso, tente outro.
                </h6>
              <?php } ?>

              <?php if($this->view->erroCadastro == 'campos'){ ?>
                <h6 class='form-text text-danger text-center'>
                  *Verifique se todos os campos foram preenchidos corretamente.
                </h6>
              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  